# Essential 
application:
  name: go-echo-boilerplate
  port: 8080
  version: 1.0.0
  environment: prod
  host: localhost
  timeout: 10
  timezone: "Asia/Jakarta"
postgresql:
  name: postgres
  user: postgres
  password: postgres
  host: localhost
  port: 5888
  ssl_mode: disable
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: "1h"
authorization:
  issuer: go-echo-boilerplate
  access:
    secret: dev-access-secret
    duration: 1h
  refresh:
    secret: dev-refresh-secret
    duration: 1h
  api_key: secret
hash:
  salt: kjwkdjkwdjkwdjk389u3ijdjd3ij-0--00i39i3di93di
cors:
  allowed_origins: ["http://localhost:3000"]
  headers_allowed: ["X-API-Key"]

# Third Party
google:
  client_id: ""
  client_secret: ""
  redirect_uri: ""
  state: ""
  user_info_url: "https://www.googleapis.com/oauth2/v2/userinfo"